version: 1.0.{build}
branches:
  only:
  - develop
  - feature/*
build_script:
- nuget restore ./HereIAm/HereIAm.sln
- msbuild "HereIAm\HereIAm.sln" /verbosity:minimal /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"
test_script:
- nunit-console "HereIAm\HereIAm.Test\bin\Debug\HereIAm.Test.dll"
build:
  publish_azure: true